package test_sql;



import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

public class AdminOptions extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptions
     */
    public AdminOptions() {
    	getContentPane().setBackground(new Color(0, 255, 0));
    	getContentPane().setPreferredSize(new Dimension(369, 400));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Add_Employee = new javax.swing.JButton();
        Add_Employee.setToolTipText("");
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 15));
        jLabel1.setForeground(Color.BLUE);
        jLabel1.setLabelFor(this);
        Add_Salary = new javax.swing.JButton();
        Update_Salary = new javax.swing.JButton();
        Update_Salary.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		EmployeeSalaryUpdate.main(new String[]{});
        		frame.dispose();
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Add_Employee.setText("Add Employee");
        Add_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
                frame.dispose();
            }
        });

        jLabel1.setText("Employee Payroll Management System");

        Add_Salary.setText("Add Salary");
        Add_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
                frame.dispose();
            }
        });

        Update_Salary.setText("Update Salary");
        
        Employee_payslip = new JButton();
        Employee_payslip.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		EmployeePayslip.main(new String[]{});
        		frame.dispose();
        	}
        });
        Employee_payslip.setText("Employee Payslip");
        
        List_Employes = new JButton();
        List_Employes.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		EmployeeList.main(new String[]{});
            	frame.dispose();
        		
        	}
        });
        List_Employes.setText("List Employes");
        
        Delete_Employee = new JButton();
        Delete_Employee.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		EmployeeDelete.main(new String[]{});
            	frame.dispose();
        	}
        });
        Delete_Employee.setText("Delete_Employee");
        
        Logout = new JButton();
        Logout.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		AdminLoginOurs.main(new String[]{});
            	frame.dispose();
        	}
        });
        Logout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(146)
        			.addComponent(Logout, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(146, Short.MAX_VALUE))
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addGap(81)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(Add_Employee, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        				.addComponent(Add_Salary, GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        				.addComponent(Update_Salary, GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        				.addComponent(List_Employes, GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        				.addComponent(Employee_payslip, GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        				.addComponent(Delete_Employee, GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
        			.addGap(65))
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap(126, Short.MAX_VALUE)
        			.addComponent(jLabel1)
        			.addGap(52))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(6)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(Add_Employee)
        			.addPreferredGap(ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
        			.addComponent(Add_Salary)
        			.addGap(18)
        			.addComponent(Update_Salary)
        			.addGap(18)
        			.addComponent(Employee_payslip)
        			.addGap(18)
        			.addComponent(List_Employes)
        			.addGap(18)
        			.addComponent(Delete_Employee)
        			.addGap(30)
        			.addComponent(Logout)
        			.addGap(44))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	EmployeeSalary.main(new String[]{});
    	frame.dispose();
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	EmployeeDetails.main(new String[]{});
    	frame.dispose();
    }                               
     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame = new AdminOptions();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify  
    static AdminOptions  frame;
    private javax.swing.JButton Add_Employee;
    private javax.swing.JButton Add_Salary;
    private javax.swing.JButton Update_Salary;
    private javax.swing.JLabel jLabel1;
    private JButton Employee_payslip;
    private JButton List_Employes;
    private JButton Delete_Employee;
    private JButton Logout;
    // End of variables declaration                   
}
