

package test_sql;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Color;
import javax.swing.JLabel;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author srinu
 */
public class EmployeeSalary extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeSalary
     */
    public EmployeeSalary() {
    	getContentPane().setBackground(new Color(0, 255, 0));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Employee Salary Details");

        jLabel2.setText("HRA");

        jLabel3.setText("DA");

        jLabel4.setText("PF");

        jLabel5.setText("Basic Salary");

        jLabel6.setText("ID");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Insert Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        Back = new JButton("Back");
        Back.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		AdminOptions.main(new String[]{});
				frame.dispose();
        	}
        });
        
        JButton btnHRA = new JButton("Enter HRA");
        btnHRA.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String result = (String)JOptionPane.showInputDialog(
        	               frame,
        	               "", 
        	               "",            
        	               JOptionPane.PLAIN_MESSAGE,
        	               null,            
        	               null, 
        	               "Enter HRA"
        	            );
        	            //if(result != null && result.length() > 0){
        	            //   label.setText("You selected:" + result);
        	            //}else {
        	            //   label.setText("None selected");
        	            //}
        				//System.out.println(result);
        				jLabel2.setText(result);
        				HRA = result;
        	}
        });
        
        JButton btnDA = new JButton("Enter DA");
        btnDA.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String result = (String)JOptionPane.showInputDialog(
     	               frame,
     	               "", 
     	               "",            
     	               JOptionPane.PLAIN_MESSAGE,
     	               null,            
     	               null, 
     	               "Enter DA"
     	            );
     	            //if(result != null && result.length() > 0){
     	            //   label.setText("You selected:" + result);
     	            //}else {
     	            //   label.setText("None selected");
     	            //}
     				//System.out.println(result);
     				jLabel3.setText(result);
     				DA = result;		
        		
        			}
        	});
        
        
        JButton btnPF = new JButton("Enter PF");
        btnPF.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String result = (String)JOptionPane.showInputDialog(
     	               frame,
     	               "", 
     	               "",            
     	               JOptionPane.PLAIN_MESSAGE,
     	               null,            
     	               null, 
     	               "Enter PF"
     	            );
     	            //if(result != null && result.length() > 0){
     	            //   label.setText("You selected:" + result);
     	            //}else {
     	            //   label.setText("None selected");
     	            //}
     				//System.out.println(result);
     				jLabel4.setText(result);
     				PF = result;
        	}
        });
        
        JButton btnBasic = new JButton("Enter Basic Salary");
        btnBasic.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String result = (String)JOptionPane.showInputDialog(
     	               frame,
     	               "", 
     	               "",            
     	               JOptionPane.PLAIN_MESSAGE,
     	               null,            
     	               null, 
     	               "Enter Basic Salary"
     	            );
     	            //if(result != null && result.length() > 0){
     	            //   label.setText("You selected:" + result);
     	            //}else {
     	            //   label.setText("None selected");
     	            //}
     				//System.out.println(result);
     				jLabel5.setText(result);
     				Basic_Salary = result;
        	}
        });
        
        JButton btnBonus = new JButton("Bonus");
        btnBonus.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String result = (String)JOptionPane.showInputDialog(
      	               frame,
      	               "", 
      	               "",            
      	               JOptionPane.PLAIN_MESSAGE,
      	               null,            
      	               null, 
      	               "Enter Bonus"
      	            );
      	            //if(result != null && result.length() > 0){
      	            //   label.setText("You selected:" + result);
      	            //}else {
      	            //   label.setText("None selected");
      	            //}
      				//System.out.println(result);
        			lblNewLabel.setText(result);
      				Bonus = result;
        	}
        });
        
        lblNewLabel = new JLabel("Bonus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(44, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel1)
        					.addGap(87))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(Back)
        								.addComponent(btnBasic, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(btnPF, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(btnDA, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(btnHRA, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(btnBonus, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        							.addPreferredGap(ComponentPlacement.RELATED))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel6)
        							.addGap(67)))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jButton1)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(83)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel5)
        								.addComponent(jLabel2)
        								.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        									.addComponent(jLabel4)
        									.addComponent(jLabel3))
        								.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(43)
        							.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)))
        					.addGap(56))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(20)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel6)
        				.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnHRA)
        				.addComponent(jLabel2))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel3)
        					.addGap(18)
        					.addComponent(jLabel4)
        					.addGap(33)
        					.addComponent(jLabel5))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(btnDA)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(btnPF)
        					.addGap(18)
        					.addComponent(btnBasic)))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnBonus)
        				.addComponent(lblNewLabel))
        			.addPreferredGap(ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(Back))
        			.addGap(22))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        //ID
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	String ID = jTextField1.getText();
    	//String HRA = jTextField5.getText();
    	
    	
    	
        String i=EmployeeOperations.save_salary(ID,HRA,DA,PF,Basic_Salary,Bonus);
    			if(i == "Success"){
    				JOptionPane.showMessageDialog(EmployeeSalary.this,"Salary added successfully!");
    				AdminOptions.main(new String[]{});
    				frame.dispose();
    				
    			}else{
    				JOptionPane.showMessageDialog(EmployeeSalary.this,"Sorry, unable to save! "+i);
    			}
    }                                        
                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	frame = new EmployeeSalary();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    static EmployeeSalary  frame;
    static String HRA="0",DA="0",PF="0",Basic_Salary="0",Bonus="0";
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private JButton Back;
    private JLabel lblNewLabel;
}
